### ISSUE TITLE
Notification says "Location not found"

### ISSUE THREAD

**Issue by infinitewaveparticle** [thuryn/your-local-weather#102]
I only use a manual location. I have disabled Location 0 and Location on my phone. The "Your local weather" notification says "Location not found" instead of my manually entered location. The weather displays correctly, but it should say my manual location instead of Location not found.

**Comment by thuryn** [comment]
Could you, please, describe the way how to get the into this state. It works fine for me, but I'm probably missing something.

**Comment by infinitewaveparticle** [comment]
You have fixed it. Thank you. My apologies for not responding sooner!
