### ISSUE TITLE
[Feature request] Shorten day names in widget

### ISSUE THREAD

**Issue by Kyle2142** [thuryn/your-local-weather#103]
Hello, I'm using Android 9 with nova launcher.
Every widget with the 5 day forecast has problems with running out of horizontal space due to the day of week names, my screen is pretty large at >5 inch.

This is especially noticeable on the 4x2 widget, where the 5 days even shift upwards. I'll upload a screenshot soon

**Comment by Kyle2142** [comment]
As expected, Wednesday is the most guilty. 
<details>
<summary>4x2</summary>
<image src="https://user-images.githubusercontent.com/19349418/50088642-3dba6680-020c-11e9-9608-673cfcadf6cf.png" >
</details>
<details>
<summary>4x1</summary>
<image src="https://user-images.githubusercontent.com/19349418/50088696-68a4ba80-020c-11e9-91f6-a55760e6d368.png">
</details>

**Comment by frozenspider** [comment]
The same thing with Android 8.1.0
Please add an option to use Mon/Tue/... instead of full day names.
![screenshot_20181216-132617](https://user-images.githubusercontent.com/2077017/50154923-80ec0680-02ec-11e9-9453-8bbaff9cb8c0.png)

**Comment by thuryn** [comment]
It seams it's not the problem of week day names, but the whole graphics - icons do not fit the screen also. So I cannot see any other solution than widget with just 3 days forecast.

**Comment by frozenspider** [comment]
If that's the case, why not just 4-day forecast? Right now it looks like 4 days fit in just fine.
Also I think that using shortened day names would still be beneficial as it would make forecast look symmetric and more aesthetically pleasant.

**Comment by Kyle2142** [comment]
@thuryn I disagree.
The long names cause wasted space around the icons, which (when removed and shifted) will allow for at least one more day to be displayed correctly. If you want, I could launch good ol' ms paint and show you

**Comment by thuryn** [comment]
I'm not able to show N days until N+1st day is display incorrectly, because I cannot see in app it's displayed incorrectly.
I can just add 2 more widgets with 3 and 4 days forecast.

**Comment by Kyle2142** [comment]
I've never done android development, so I'm not sure what's feasible or not.

Perhaps you can get the dimensions of the widget and use that to make a guess?
I know OmniJAWS widgets are pretty solid, it updates the contents upon resize

**Comment by thuryn** [comment]
Implemented in v 4.6.1 - you can set short day names and a number of days in the forecast also
