### ISSUE TITLE
Widget not auto updating after most recent update

### ISSUE THREAD

**Issue by infinitewaveparticle** [thuryn/your-local-weather#108]
See Issue #98. It was fixed, but now is no longer working again.

**Comment by ghtux** [comment]
Yes, updating died again with latest version 😩

**Comment by thuryn** [comment]
could you, please, give me a log file again. I would like to do my best to get it to work on your devices

**Comment by ghtux** [comment]
Updating to 4.6.3 solved it!

Next time I will attach logs, sorry for being lazy 😅

**Comment by thuryn** [comment]
OK, I consider this issue as solved. If there is any problem, reopen this issue or create the new one.
