### ISSUE TITLE
graph widget doesn't refresh

### ISSUE THREAD

**Issue by jpritikin** [thuryn/your-local-weather#111]
Android 9.0.11 Version 4.6.2

The graph widget doesn't refresh automatically. It does update if I manually go into the app and touch the refresh button. Shouldn't it update automatically?

**Comment by thuryn** [comment]
Yes it should refresh automatically (according the update period, but not earlier then once per hour

**Comment by jpritikin** [comment]
Well, it doesn't update. If I refrain from opening the app then the widget keeps showing the same info for days. It was still showing Monday today until I opened the app and then it updated to Fri.

**Comment by jpritikin** [comment]
Seems fixed in version 4.6.9

**Comment by infinitewaveparticle** [comment]
@thuryn Is it the widget that won't uodate more than once per hour - or the weather itself? I ask because the option exists in settings to update once every 30 minutes

**Comment by infinitewaveparticle** [comment]
And 15 mins for that matter

**Comment by thuryn** [comment]
Weather and widget should be updated at once - when you set 15 minutes update interval the weather and the widget should be updated every 15 minutes
