### ISSUE TITLE
Request: Keep weather data of current day

### ISSUE THREAD

**Issue by cabroncito** [thuryn/your-local-weather#112]
I like the app, especially the multi-diagram. But I'm always somewhat puzzled which time the diagram shows. Turns out, the (first) vertical line is not 0:00 am (day change) but close to the current time. This makes reading the diagram less intuitive for me. Please make the vertical lines a fixed time - I think 0:00 a.m. is best. Thanks in advance!
EDIT: typos

**Comment by cabroncito** [comment]
Thanks man!
Now I see two vertical lines for each day: a bright one fixed at 0 a.m. and a slightly darker one fixed at 12 a.m. Perfect!
Minor thing though: When updating the weather data, more vertical lines in different tones appear and it's hard to tell what they show. Workaround: change to daily forecast view and then back to graphics view. Then you'll see the only the correct bright and darker lines as mentioned above.

**Comment by thuryn** [comment]
I'll check the issue, thank you for reporting @cabroncito

**Comment by thuryn** [comment]
Hi,
  the small issue is fixed in version 4.7.4.

Regards,
Tomas

Dne sobota 6. dubna 2019 8:26:45 CEST, cabroncito napsal(a):
> Thanks man!
> Now I see two vertical lines for each day: a bright one fixed at 0 a.m. and
> a slightly darker one fixed at 12 a.m. Perfect! Minor thing though: When
> updating the weather data, more vertical lines in different tones appear
> and it's hard to tell what they show. Workaround: change to daily forecast
> view and then back to graphics view. Then you'll see the only the correct
> bright and darker lines as mentioned above.

**Comment by cabroncito** [comment]
Works like a charm now. Thanks man, you're the best!
