### ISSUE TITLE
Notification issues

### ISSUE THREAD

**Issue by infinitewaveparticle** [thuryn/your-local-weather#115]
1. In 'Settings', clicking on 'Notification settings' causes the app to crash every time.

2. The permanent notification is no longer shown. From time to time it appears, but it eventually stops updating. Opening the app causes it to disappear again. See above.

App version 4.6.9

This is my favorite weather app. I'm hoping the bugs are worked out soon.

**Comment by thuryn** [comment]
Could you, please version >= 4.6.10? If it does not help could you, please, send application and/or logcat log?

**Comment by infinitewaveparticle** [comment]
Updating to 4.6.10 helped, but the notification disappears when I open the app. It comes back when I open notification settings.

**Comment by thuryn** [comment]
Is thi situation like this: you have set permanent notification, but when you leave the app the notification goes away - does it work in this way?

**Comment by infinitewaveparticle** [comment]
@thuryn No... the notification is present at the top of the screen, but it disappears when I bring the app to the foreground. I have to open Notification Settings for it to reappear. However, today the crash started happening again (version 4.6.10) every time I click on Notification Settings. I updated to 4.7.1, but it's still happening. The app crashes every single time I click on Notification Settings....

**Comment by thuryn** [comment]
I'm sorry for this troubles. Could you, please, send me logcat when the app crashes?

**Comment by infinitewaveparticle** [comment]
@thuryn The crash only happens when I'm connected via WiFi. It doesn't happen when it's connected via cellular. Hiw do I send you the log? I don't have email on this device, but I can use Signal or Firefox Send.

**Comment by thuryn** [comment]
You can send me the logs by email (it's preferred way). You can send the logs by Telegram also (username is thuryn).

**Comment by DorianDay1** [comment]
I also:

1.   In 'Settings', clicking on 'Notification settings' causes the app to crash every time. (Been working with it for 2 hrs, Now seems fixed!)

2.   The permanent notification is no longer shown. (Don't know if it will reapear, yet.) 
-LG G5 tmob 

*I will send debug log, Was I supposed to do that before it partly fixed?


Love your app apart from this, TY, will send some coffees!!

**Comment by DorianDay1** [comment]
Update:
"2." Status bar is now working!
(I think it just needed time to 'update' according to settings.)
*I can also open app and it doesn't disappear.
-What appears to have fixed this was setting 'Update location and weather' & 'Power save options' to DEFAULT.
--BOTH were necessary.
*Also, ''Notification Settings" HAD TO be the first settings set-up after fresh install.
TY.

**Comment by BeeeWall** [comment]
It looks like it only happens when it's set to show temperature as the icon. Logcat:

```
04-08 07:23:05.407 E/ourlocalweathe(20498): Not starting debugger since process cannot load the jdwp agent.
04-08 07:23:33.087 E/AndroidRuntime(20498): FATAL EXCEPTION: main
04-08 07:23:33.087 E/AndroidRuntime(20498): Process: org.thosp.yourlocalweather, PID: 20498
04-08 07:23:33.087 E/AndroidRuntime(20498): java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=yourLocalWeather pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x12 color=0x00000000 vis=PUBLIC)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:393)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.NotificationManager.notify(NotificationManager.java:370)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.NotificationManager.notify(NotificationManager.java:346)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at org.thosp.yourlocalweather.utils.NotificationUtils.showNotification(NotificationUtils.java:100)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at org.thosp.yourlocalweather.utils.NotificationUtils.weatherNotification(NotificationUtils.java:48)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at org.thosp.yourlocalweather.SettingsActivity$NotificationPreferenceFragment.entrySummary(SettingsActivity.java:651)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at org.thosp.yourlocalweather.SettingsActivity$NotificationPreferenceFragment.updateSummary(SettingsActivity.java:677)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at org.thosp.yourlocalweather.SettingsActivity$NotificationPreferenceFragment.onSharedPreferenceChanged(SettingsActivity.java:683)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.preference.Preference.tryCommit(Preference.java:1590)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.preference.Preference.persistString(Preference.java:1626)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.preference.ListPreference.setValue(ListPreference.java:148)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.preference.ListPreference.onDialogClosed(ListPreference.java:283)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.os.Looper.loop(Looper.java:193)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at java.lang.reflect.Method.invoke(Native Method)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-08 07:23:33.087 E/AndroidRuntime(20498): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by thuryn** [comment]
Nice, thank you for the log @BeeeWall I'll check this

**Comment by thuryn** [comment]
@BeeeWall  I cannot reproduce the issue. What device do you have? The Android version, the screen resolution and a screenshot of Notification setting would be helpful (if possible).

**Comment by BeeeWall** [comment]
Moto X4 running LineageOS 16 (Android Pie), resolution is 1080x1920, DPI is set to 294 ("Smallest" in Display Size settings). 

According to a quick google, this error means exactly what it says, there's no small icon set. But then that doesn't make sense, because as @DorianDay1 says, if you set Notification Settings first and then do not touch any other settings it works.

**Comment by BeeeWall** [comment]
Do you mean a screenshot of the app's Notification Settings or the system settings?

**Comment by thuryn** [comment]
app's Notification Settings

**Comment by BeeeWall** [comment]
Here:
![](https://i.imgur.com/lsslfR7.png) 

Changing the icon to Temperature immediately crashes the app, and crashed every time I try to go into notification settings (which is why it's not set to temp in the screenshot).

**Comment by thuryn** [comment]
@BeeeWall could you, please, apk here: https://de-next.owncube.com/index.php/s/zie8dYZqT63W7q4

I've just replaced Android function which can cause the problem.

**Comment by DorianDay1** [comment]
Hi thuryn,
You may have sent this email to me by mistake.
I am dorianday1 not beeewall.
Either way, i downloaded the new app and it fixed several problems for me.
Thx you.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BeeeWall** [comment]
That build doesn't crash, yay. Although the temperature in the icon isn't right, it says -50 (the temp in the notification and app is like 40, so it's just the icon).

**Comment by thuryn** [comment]
@BeeeWall  sorry, I've made a stupid mistake regarding the -50 issue. I've just uploaded new version to try ;-)

**Comment by infinitewaveparticle** [comment]
@thuryn what is the link for this latest version? I, too, have the temperature as my icon. Perhaps it will fix my new issue of not working at all on cellular (see newest issue)

**Comment by infinitewaveparticle** [comment]
p.s. My apologies for not sending the logcat. I don't have email and my damn Telegram account auto-deleted, lol

**Comment by infinitewaveparticle** [comment]
@thuryn Actually I tried installing the apk from the link posted above, but the app would not install (wouldn't update my current version of the app). I'm assuming something isn't lining up on the hash values.

**Comment by thuryn** [comment]
Yes, the version is the same, the build is new. Does the temperature work?

**Comment by BeeeWall** [comment]
@thuryn it works now, thanks a lot!

@infinitewaveparticle I assume the uploaded build has a different signature from your current version (especially if you got it from F-Droid, because they use their own key there). You'll have to uninstall the app and then install the APK. Note that you may then have to do that again to get updates, I'm not sure.

**Comment by infinitewaveparticle** [comment]
@BeeeWall Yes I suspected I would need to do that. I typically use Yalp Store, APKGrabber, APKPure, & F-Droid for app updates. I've been updating "Your local weather" from APKPure. I'm gonna check to see if the new release is pushed to these sites first. If not, then I'll uninstall and do the straight apk link.
