### ISSUE TITLE
Impossible to add city manually

### ISSUE THREAD

**Issue by Zoldiru** [thuryn/your-local-weather#120]
On Android 4.4.4, I cannot add city manually, nothing happens when I touch the add button.

**Comment by sm4rk0** [comment]
Do you already have one location added? If so, it's duplicate of #113.

**Comment by Zoldiru** [comment]
No, I don't have any location added yet.

**Comment by thuryn** [comment]
I can confirm this bug. It seams that FloatingActionButton does not work on Android 4 at all. I'll move this action into action bar for Android 4. Sorry for this inconvenience.

**Comment by thuryn** [comment]
it's fixed already
