### ISSUE TITLE
Persistent Notification always displays '50', etc

### ISSUE THREAD

**Issue by infinitewaveparticle** [thuryn/your-local-weather#126]
Two issues:

1) No matter what I do, when I select to show the temperature as the Notification it constantly displays 50. I use Fahrenheit & "when updates regularly" for updates, if that helps.

2) When I turn the Notification off entirely (in the app setting) it still displays the Notification no matter what setting it's on.

**Comment by cwesson** [comment]
I have the same problem with constantly displaying 50.

I looked through the code some, it appears it only has icons for -50 to 50.  This seems like a reasonable range for Celsius, but for Fahrenheit a more reasonable range would be -60 to 120.  I also noted that there are icons for ">50" and "<50", but the code doesn't use them.

I might take a shot at fixing this myself, but I'm not sure how the icons were generated.
