### ISSUE TITLE
°C/°F bug when switching the widgets day/3x hr. setting 

### ISSUE THREAD

**Issue by Locash** [thuryn/your-local-weather#135]
When changing the widget's "number of days for the forecast"  (3,4,5 days/3x,4x,5x{3 hr intervals}.
The 3,4,5 days is in °F(as set) but when changed over to 3 hr. Intervals it displays it in °C but labeled as °F.

It occurred with previous f-droid ver. 4.7.6 and current 4.7.7, also tried clear cache and data, along with a few un/reinstalls.

![Untitled15](https://user-images.githubusercontent.com/30946440/62958615-b46c2b80-bdbc-11e9-9782-9fbe0a504a73.png)

**Comment by thuryn** [comment]
I'll check this.

**Comment by thuryn** [comment]
I've found the bug, fix will be available in 4.7.9 version. Sorry for the confusion.
