### ISSUE TITLE
Cannot disable notifications

### ISSUE THREAD

**Issue by AntiSol** [thuryn/your-local-weather#136]
Hi, thanks for the app, i've been using it for ages.
Recently there was an update (f-droid) and now i have a notification that i can't get rid of. The option to turn it off is disabled:
![Screenshot_20190816-020925](https://user-images.githubusercontent.com/351169/63109025-8c9ee280-bfcb-11e9-82f6-7a6428875f84.png)

Any help would be appreciated. Thanks! :)

**Comment by thuryn** [comment]
When you select update by accelerometr, the persistent notification is obligatory. Android kill the app otherwise.

**Comment by AntiSol** [comment]
OK. I turned off the accelerometer and now I have the option to disable notifications, but when I turn off the notification it seems to come back after a while. If I go back into settings it has notifications turned off but the notification is there. I can turn it on and back off but then it comes back again after a while (maybe a few hours)

**Comment by rappelkiste** [comment]
I love this APP. But I have the same notification "problem" and I can't get rid of it. It appears again and again after the selected time. But the notification is turned off and the time is grayed out.

**Comment by thuryn** [comment]
I'll try to simulate the issue on my phone and fix it.

**Comment by AntiSol** [comment]
oh cool, thanks! I'll need to wait for the new version to show up in f-droid (unless you can point me to an apk?) but as soon as it does I'll let you know whether it's fixed :)

**Comment by AntiSol** [comment]
I got the new version and I've had the wisget running for about 10 hours now an the notification hasn't popped up, so it looks like this is solved. Thanks so much :)

**Comment by Lee-Carre** [comment]
@thuryn 

> … persistent notification is obligatory. Android kill the app otherwise
 
Only if `Optimise battery usage` hasn't been disabled for the app (for it to be able to request, of the OS, that it not be killed). If `Optimise battery usage` *is* disabled, then a persistent notification *shouldn't* be needed.

One of the problems with persistent notifications is with usability: the user then ignores said notification. When it's merely a token (that some app is running in the background) then this may be a non-problem.

However, for the likes of weather notifications, then how would the user know (short of closely examining the notification each time) that there's some new relevant weather info (e.g. that he's about to be rained on, and should find shelter or use his umbrella).
