### ISSUE TITLE
Meaning of second temperature number on widget?

### ISSUE THREAD

**Issue by iillyyaa2033** [thuryn/your-local-weather#143]
![Screenshot_20191124-001449](https://user-images.githubusercontent.com/17745136/69485381-bb8ce600-0e4f-11ea-93d3-050e148f3e73.png)
On picture above you can see widget with forecasts for next five days. For each day drawn day name, cloud icon and two numbers. 

For example, Monday is cloudly and will be '-5/0°C'. But what second number (zero) means? This is not a daily/nightly temperature, nor a humidity, nor a pressure:
![Screenshot_20191124-002201](https://user-images.githubusercontent.com/17745136/69485456-cd22bd80-0e50-11ea-9f3c-77ab6e161c77.png)

What is it?

**Comment by dugite-code** [comment]
Min/Max degrees C. As far as I can tell it's not displayed anywhere else outside of the Temperature graphs.

**Comment by iillyyaa2033** [comment]
I assume that max degress value calculated wrong.

As you can see in table, max temp is -3°C, not 0.

**Comment by thuryn** [comment]
Well, it seams to be a serious problem, I'll check it

**Comment by thuryn** [comment]
Fixed in version 5.1.2. Sorry for the inconvenience.

**Comment by iillyyaa2033** [comment]
Its fine. Looking forward to seeing update on FDroid.

**Comment by iillyyaa2033** [comment]
Looks like everything is fine now. Thank you!
