### ISSUE TITLE
Graph Widget Issue

### ISSUE THREAD

**Issue by chris777c** [thuryn/your-local-weather#144]
Hello,

I have problem on graph widget for nova launcher, see screenshot it's better explication : 
![Screenshot_20191223-223556_Nova_Launcher_1](https://user-images.githubusercontent.com/33424905/71381786-5b679c00-25d5-11ea-830e-8879b3b7b72a.png)

**Comment by thuryn** [comment]
I'll install a Nova launcher and check it

**Comment by thuryn** [comment]
I've just installed Nova launcher and tried 2 widgets and it works fine. What OS version, Nova lanuncher version and resolution do you have?

**Comment by chris777c** [comment]
Hello,

Nova launcher prime : 6.2.3
OS : lineageOS 16 (Android 9)
Résolution : 1080p

**Comment by thuryn** [comment]
Well, I've just installed Nova on my phone with openkirin build (it's not lineage, but it's similar) and works fine. Does this problem happen for all widgets?

**Comment by chris777c** [comment]
No only graph widget

**Comment by thuryn** [comment]
I've just tried the graph-only widget and it works fine also. What grid setting do you use in Nova launcher?

**Comment by chris777c** [comment]
Hello,

I use 5x4 grid
OS : lineageOS 16 (Android 9)
Résolution : 1080p

**Comment by thuryn** [comment]
Thank you, it works for me also. You can try one more option - in the app menu you select Settings/Widget settings and you can find the option "Show graph in native resolution (when the graph is too small)" - try to check it, please.

**Comment by chris777c** [comment]
Good, I uncheck option "Show graph in native resolution ans it work, thank you!!
