### ISSUE TITLE
Create bar graph instead of line one as an option

### ISSUE THREAD

**Issue by thuryn** [thuryn/your-local-weather#16]

**Comment by cocker-cc** [comment]
**+1**  
especially the Rain- and Snow-Graphs should consist of Bars.  Width of each Bar represents the Time-Interval, the Height represents the Millimeters fallen in that Time-Interval.  A Line-Graph is not usable in that Case.

**Comment by thuryn** [comment]
Thank you for using my app. You request is planned feature request, see:
https://github.com/thuryn/your-local-weather/issues/16

Regards,
Tomas


2018-05-17 13:45 GMT+02:00 cocker-cc <notifications@github.com>:

**Comment by thuryn** [comment]
Implemented in v 4.6.1
