### ISSUE TITLE
Disable Toasts 

### ISSUE THREAD

**Issue by franz-xaver-hallhuber** [thuryn/your-local-weather#168]
Although I have only entered manual locations, I constantly get the Toast message "Permissions not yet granted". Can you please disable?

**Comment by thuryn** [comment]
What version of Android do you have?

**Comment by franz-xaver-hallhuber** [comment]
Android 9

**Comment by thuryn** [comment]
Could you, please, to click on magnifier icon and move location 0 left - you can find the disable button underneath. Click on disable and check the result, please.
