### ISSUE TITLE
Not complete view with bigger font in vertical view

### ISSUE THREAD

**Issue by paulle** [thuryn/your-local-weather#17]
Not complete view with bigger font in vertical view (in German version), maybe there shoud be a line wrap. See screen shot.
![screenshot_20180125-175736](https://user-images.githubusercontent.com/4852079/35766763-21940e0c-08de-11e8-827d-80e81be02bbc.png)
![screenshot_20180125-175747](https://user-images.githubusercontent.com/4852079/35766764-21b1ff34-08de-11e8-9eb5-801037256401.png)

**Comment by thuryn** [comment]
Fixed in version 2.4.1

**Comment by paulle** [comment]
Thank you

Am 14. Februar 2018 23:26:34 MEZ schrieb thuryn <notifications@github.com>:
>Fixed in version 2.4.1

-- 
K-9 Mail
