### ISSUE TITLE
"Access expired. Upgrade the app, please."

### ISSUE THREAD

**Issue by sys-3** [thuryn/your-local-weather#173]
I am running the latest version, 5.7.0. I think your API key has expired.

**Comment by gbakeman** [comment]
When I had updated the app with my userdata, I wasn't seeing that error in the title, but I was getting a toast notification saying an error occurred. When I wiped my data, I could then see the above error message too.

**Comment by jnareb** [comment]
The latest version on F-Droid is 5.6.1, while the last release is 5.7.x

**Comment by gbakeman** [comment]
The latest version I have from F-Droid is 5.7.0, which is when I first noticed this issue.

**Comment by Beeblebrox21** [comment]
I have this issue with 5.7.0 from F-Droid and Witz 5.7.1 from Google Play Store.

**Comment by erronfield** [comment]
I was having the same issue with v5.7.0 from F-Droid. Uninstalled and reinstalled from Google Play for v5.7.2 and issue is resolved.

**Comment by doobydooby72** [comment]
Did the same as the above and reverted to play store variant... Shame, love fdroid. Please update them in parity... Perhaps remove or update the aptoide link too. Or if anyone has the knowlegde and access build and host your own repo for us. I know a 3rd party repo is the only reason i get day 1 newpipe updates otherwise mad delay.

**Comment by Beeblebrox21** [comment]
OK. v5.7.2 from Google Play Store has a workaround. This works ...

**Comment by gbakeman** [comment]
Version 5.7.1 (released to F-Droid now) has an updated API key and seems to be working.

**Comment by mithrandir42** [comment]
For me 5.7.1 crashes after the upgrade. Do I have to wipe after the update?

**Comment by gbakeman** [comment]
It might be worth a shot. I was starting with no data so it seemed to work for me.

**Comment by mithrandir42** [comment]
Thanks, after clearing app data it worked again
