### ISSUE TITLE
Notification: black text, black background

### ISSUE THREAD

**Issue by toas-koas** [thuryn/your-local-weather#174]
When my phone turns to night mode, the notification bar turns black. The text from the notification also stays black, which is why you can't see anything then.

![Screenshot_20210311-183850_Fennec](https://user-images.githubusercontent.com/74021807/110831018-20b15880-829a-11eb-9660-a78042ef3ece.png)

**Comment by toas-koas** [comment]
I just see this is only the case when I select custom as the notification style.

**Comment by thuryn** [comment]
Fixed in version 5.8.20
