### ISSUE TITLE
Add string for Croatian language

### ISSUE THREAD

**Issue by milotype** [thuryn/your-local-weather#178]
Please add the string for Croatian language to all translation files:

```
#, java-format
msgctxt "pref_language_hr"
msgid "Hrvatski (Croatian)"
msgstr ""
```

I've translated the app into Croatian ... more or less 100%.

**Comment by thuryn** [comment]
I can see you've added it already. I'm going to make fixies because of Android 11 and relese new build with the all language translations.

**Comment by milotype** [comment]
@thuryn ??? (I did not add anything ...)
Maybe you misunderstand my issue ... 

In the Strings file at Weblate there are many languages defined in English and they can be "translated", for instance:
Српски (Serbian)
Slovenščina (Slovenian)
Polski (Polish)

But "Hrvatski (Croatian)" isn't specified yet and I was asking you to add that string into the source string file so it can be translated as well.

**Comment by thuryn** [comment]
I see, ok I'll add it.

**Comment by thuryn** [comment]
I've added Crotian language. Check it, please. I would like to release new build at the start of the next week.

**Comment by milotype** [comment]
Thank you. It is implemented in Weblate ...
