### ISSUE TITLE
License? Paid options?

### ISSUE THREAD

**Issue by lu-as** [thuryn/your-local-weather#181]
Hi,
since quite a while I miss the option to add more than two locations.
Now, I just discovered the option "paid/extended functions" in the settings menu, along with the option to enter a license key. But unfortunately no clue where to obtain such a key. Any hints?
Thanks in advance!
Lennart

**Comment by Maxwellfire** [comment]
I believe that this refers to a premium openweathermap.com API key which allows you to have access to more things. See here: https://openweathermap.org/price

The main thing that it gives you seems to be hourly forecasts instead of 3 hour ones.

**Comment by thuryn** [comment]
I'm going to prepare the paid option for update of weather forecast. I have no more details about that right now.
