### ISSUE TITLE
Selected and actual language mismatch

### ISSUE THREAD

**Issue by f-florian** [thuryn/your-local-weather#183]
Version 5.7.5 on /e/ (I apologize if this bug is already fixed but I find no similar bug, either open or closed).
When selecting a language in the Settings->General Settings-> Language menu, the actual language being use for the translation is the one following the selected one.
E.g., in order to get English, Nederlands(Dutch) has to be selected.

![photo_2022-02-18_19-25-01](https://user-images.githubusercontent.com/6330150/154741997-ec61a6fe-9616-4b57-a52b-667411698c58.jpg)

Selecting English many app strings are displayed in Finnish (the next language).
![photo_2022-02-18_19-35-02](https://user-images.githubusercontent.com/6330150/154742469-5f6978be-f9b2-4807-9964-6355a7491e43.jpg)

Note that selecting the last language (Vietnamese) makes the app crash.

**Comment by thuryn** [comment]
Fixed in v5.7.7
