### ISSUE TITLE
[CRASH] for many reasons

### ISSUE THREAD

**Issue by ildar** [thuryn/your-local-weather#187]
is the app supported by anyone?
Android 13.

**Comment by ildar** [comment]
ok, now the app mostly doesn't crash o Android 13.
But it still crashes in the `Guidance settings` (TTS) on any Android version.

**Comment by ildar** [comment]
with version 5.8.9:
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/10611306/log-yourlocalweather.txt)
[adb.logcat.txt](https://github.com/thuryn/your-local-weather/files/10611307/adb.logcat.txt)

**Comment by thuryn** [comment]
Sorry fot the late response, I believe this bug is already fixed. Check the new version, please.
Keep in mind, that there are location sensitive information in the log file, so it's better to send me the log file by email.

**Comment by thuryn** [comment]
fixed in v5.8.15
