### ISSUE TITLE
Blank Forecast and Graphs pages, no data in Widget

### ISSUE THREAD

**Issue by davoper** [thuryn/your-local-weather#189]
Although Current Weather is showing correct data for selected location, Daily Forecast page is not showing any information, only picture of "Android".
Also Graphs are showing as empty with text "No chart data available".

Widget for 4x1 forecast is also blank, while regular 3x1 current weather widget is showing data.

This is on Android v12, with version 5.8.9, using custom openweathermap API key I entered into YLW setup.

5.6.4 version on another Android 9 device is working ok in all above cases for the same location.
(also using custom API key generated by the same openweathermap user)

Please let me know if more information is need to debug.

**Comment by davoper** [comment]
Installed version 5.8.13 today, and the difference is that now both Daily Forecast and Graphs screens are constantly and rapidly showing Loading... dialog which closes and opens again every ~0,5 second.
Do exit this loop I need to swipe the application away.
Main screen - Current Weather is working as expected

**Comment by thuryn** [comment]
OK, could you, please, send me application log file?

**Comment by davoper** [comment]
Here is the log (private info removed/replaced)
https://pastebin.com/9VZGcYBb

**Comment by thuryn** [comment]
fixed in v5.8.15

**Comment by davoper** [comment]
Tried again on v5.8.16 from f-droid and the issue was resolved only after I cleared all app cache+data.
(clearing app+cache was not helping in the earlier versions)
So I guess it works now correctly - thanks.
