### ISSUE TITLE
Cancel finding location

### ISSUE THREAD

**Issue by Dogora** [thuryn/your-local-weather#21]
Please add a cancel button so I can tell the app to stop trying to find the current location. It just runs and runs for me, so I basically have to kill the app. However, when I restart it, the current location is there. It seems to work in the end, but never finishes by itself.

I'm running Resurrection Remix 5.8.5, which is based on LineageOS 14. I do not have any GApps installed.

**Comment by thuryn** [comment]
Well, I've seen this problem yet, so I have to look after the problem and I'll add the cancel button too.

**Comment by thuryn** [comment]
Fixed in version 2.4.2
