### ISSUE TITLE
"True" Imperial units

### ISSUE THREAD

**Issue by Dogora** [thuryn/your-local-weather#22]
Please include miles/hour when selecting Fahrenheit. Inches of mercury would also be nice for the barometric pressure. Us USA-based users will appreciate this. :-)

**Comment by thuryn** [comment]
Implemented in version 2.5

**Comment by jcp-sd** [comment]
I myself would personally prefer keeping the widgets for selecting units for temperature and wind speed separate as they are now. Another unit for wind speed that some users (aviators and sailors both) would appreciate is knots (or nautical miles per hour).

I have the following for conversion (from the Unix/Linux units application);

Multiply wind speed in m/s * 1.9438445 to get nautical miles per hour (knots).

**Comment by thuryn** [comment]
Available in version 3.0
