### ISSUE TITLE
More information is needed when searching for location

### ISSUE THREAD

**Issue by Dogora** [thuryn/your-local-weather#23]
I live in Vienna, which is a very popular name for a town. When I search for it, I get many results for "Vienna US". Please add more information to the search results, such as geo coordinates, so I can determine which of the many "Vienna US" results is where I actually am. There's no indication which one I chose.

Fortunately, there is a town very close to me with a unique name.

**Comment by ildar** [comment]
Am I missing something or in the current version 2.3 we have no more city
search, just geo?

**Comment by thuryn** [comment]
@ildar  You can search the location when you uncheck update location in the settings. I'm going to add option to have more than one location - I will have the possibility to swtich between automatic updated location and locations found by search.

Regarding searching - I'm going to rewrite the search activity to use nominatim - this will give you more precise results. Moreover you can see the precise location name in the app and widget then.

**Comment by thuryn** [comment]
Available in version 3.0

**Comment by paulle** [comment]
In the current version I have no more city search, just geo?
"You can search the location when you uncheck update location in the settings."
It didn't work for me, I only have geo.

**Comment by thuryn** [comment]
Could you, please, check the magnifier icon in the main screen? I believe you find the way how to add location 😉

**Comment by paulle** [comment]
Thank you for answering, short press on the magnifier icon opens geo (the map), long press opens a button named search city, but pressing this button nothing happens.
