### ISSUE TITLE
Show notification immediately

### ISSUE THREAD

**Issue by Dogora** [thuryn/your-local-weather#24]
I like your app very much, especially with the constant notification showing the weather. However, it looks like the notification doesn't appear until the update time chosen. So, if I adjust the settings or update the app, the notification doesn't appear until an hour after I start it. My update period is an hour.

**Comment by ildar** [comment]
Yep, I see this too on a widget: manual update in the app doesn't change
the widget

**Comment by ildar** [comment]
Seems fixed. BTW crashes stopped, thanks
