### ISSUE TITLE
How to help with translations + tutorial text?

### ISSUE THREAD

**Issue by JobLeonard** [thuryn/your-local-weather#27]
Hey, happy user of the app here! 

The widget works perfectly fine so I almost never open the app "properly". I just did for the first time in ages, and being greeted by a detailed tutorial was a pleasant surprise! A few settings that I was not aware of were explained, and the app is now better tweaked to what I want it to do. Love it :)

There were a few spelling errors, for example: _"**cashing** found locations"_ instead of _"**caching** found locations"_. Also a few quirky idioms.

I figured *"Hey, I can help there! I'll just look up the text files in the source, edit them and send a pull request!"* (mind you, I'm not an Android dev - building this from scratch would be too much hassle. But editing some writing in plain text should be easy). However, I can't find the text source with a quick browse, where should I look?

Also, if you need translations, I can help with Dutch :)

**Comment by thuryn** [comment]
Hi Job,
  thank you for the praise. I'm glad to hear that somebody like the initial guide ;-)
  You can help with translation here: https://hosted.weblate.org/projects/your-local-weather/
  it's really comfortable to do it here ;-)

Thank you for help.

**Comment by JobLeonard** [comment]
Cheers, will look at it over the weekend
