### ISSUE TITLE
Quit nagging me to enable GPS

### ISSUE THREAD

**Issue by AntiSol** [thuryn/your-local-weather#28]
This might be semi-related to #21.

I run LineageOS and only turn on features like bluetooth and GPS when I want them, so my GPS is disabled most of the time. 

When I have my GPS disabled and I open the app, it nags me to go into phone settings and re-enable GPS. It's easy enough to get around this by just tapping somewhere not on the nag dialog, but it's annoying. When I want to update the location, I'll turn on GPS and press the 'detect location' button.

I tried telling it not to update the location, but in that mode the 'detect location' button disappears and it resets the location to london.

I can see how prompting the user to turn on GPS might be useful, but I'd like a setting to turn off that nag screen so that I can just update my location manually and not be bugged to enable GPS every time I want to see a forecast.

Thanks for your time :)

**Comment by thuryn** [comment]
Hi, thank you for reporting. This seems to be really bug - I havn't considered this workflow and I'm going to fix it.

**Comment by AntiSol** [comment]
Awesome, thank you!

**Comment by thuryn** [comment]
Fix available in v3.0.2 - could you confirm if it works fine for you, please?

**Comment by AntiSol** [comment]
Thanks for the patch. Apologies for the slow response, I've been waiting for the new version to show up in f-doid.

I wasn't prompted to enable GPS when starting the app, only when I tried to use gps to get my location (it also requested permission to use gps), but I'm indoors at the moment and couldn't get a fix and the app crashed repeatedly. now the app is showing no location (when it doesn't just crash) rather than my last (cached) location, and the widget is blank.

I'll play around with it a bit more tomorrow when I'm outside and can get a fix and hopefully I'll be able to tell you more. if there's a logfile or a way to get more debugging info for you to figure out the crashes let me know and I'll do that.

**Comment by pille** [comment]
v3.0.4 (from f-droid) crashes after the update while updating weather info.
daily forecast shows bogus data (25~30°C when it's around zero).

**Comment by AntiSol** [comment]
aah ok. is there an apk for a newer version I can try?

**Comment by thuryn** [comment]
The newest version is 3.0.7, hopefully available on f-droid soon.
Yes, when app is not able to get the location it shoes the message "Location not found".
I would like to know more about the bogus data - I'm not able to reproduce this issue so the log file would be helpful.

**Comment by pille** [comment]
i figure the wrong temperatures match lat 0, lon 0,
and according to the log it detected that bogus location.
it should cache the last known good location for that case.
the log contains two crashes, btw.
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/1838854/log-yourlocalweather.txt)

**Comment by thuryn** [comment]
I cannot see any crashed in the log file. But anyway, all crashes has been solved in 3.0.7 version. I can see the coordinates 0,0 in the log file. What is the scenario? Are you going outside, get the GPS fix and the you have location coordinates 0,0 ?

**Comment by pille** [comment]
GPS is disabled, as that's the scope of this issue.

**Comment by thuryn** [comment]
Well, I'm asking about to know if it works fine for you or you're missing something regarding geolocation search/watch.

**Comment by pille** [comment]
same crash and (0,0)-temperature behavior in v3.0.9.
what exactly are you asking?

**Comment by thuryn** [comment]
I see, the current version is v3.0.11, wait for it on f-droid, please. Sorry for confusion.

**Comment by AntiSol** [comment]
I've now had a chance to play around with this in the latest version on f-droid (3.0.9), and I'm satisfied that the original issue I raised is resolved. You can close this ticket if you like. Thanks! :)

**Comment by thuryn** [comment]
Perfect, thank you for message a reporting
