### ISSUE TITLE
Crashing after toggle setting "hide description"

### ISSUE THREAD

**Issue by AeliusSaionji** [thuryn/your-local-weather#3]
I checked "hide weather description" to see what it does, then unchecked it. Now the app crashes and can't be used.

I was able to replicate this after clearing data and repeating the following steps:

1. Go to settings, toggle setting
2. Back to main page, refresh data

Repeat above until app crashes upon start and can't be used.

**Comment by thuryn** [comment]
Well, I'll try to reproduce the problem and fix it.
Thank you for reporting.

**Comment by thuryn** [comment]
Fixed in version 1.7
