### ISSUE TITLE
Text wrapping in time of day column, field of Forecast page

### ISSUE THREAD

**Issue by jcp-sd** [thuryn/your-local-weather#30]
Everything looks fine on my two stupid phones, but on my (relatively larger screen) Nexus 7 tablet (size similar to the mini PearPad), the column, field that shows the time of day on the forecast page is not quite wide enough, and the text wraps when clearly there is plenty of unused room that could be allocated.

Screenshot shown below;

![screenshot_2018-02-28-23-14-56](https://user-images.githubusercontent.com/16908384/36940560-1d234536-1efa-11e8-994c-b2ae74febcd4.png)

**Comment by thuryn** [comment]
Yes, that's not well formatted, I'll fix it. I'm going to improve user experience on tablets later too.

**Comment by thuryn** [comment]
fixed in v3.0.8, check it please

**Comment by jcp-sd** [comment]
No joy I'm afraid. I could post another screenshot, but it looks just like the original one above. I verfied that I have release 3.0.8, and also did a "force stop" just for grins. I also tried fiddling with enabling, disabling some or all of the available columns. Strange...

**Comment by jcp-sd** [comment]
It's fixed in release 3.0.9 on my Nexus 7 tablet.

**Comment by thuryn** [comment]
Nice, thank you for the message
