### ISSUE TITLE
never update feature

### ISSUE THREAD

**Issue by bderembl** [thuryn/your-local-weather#31]
Is there a way to never update the weather infos (except if I manually press refresh)?
I couldn't find the option

thanks!

**Comment by thuryn** [comment]
This possibility comes with implementation of issues #12 and #23

**Comment by thuryn** [comment]
Available in version 3.0

**Comment by thuryn** [comment]
I've found I havn't fix this in the 3.0 release. Sorry. Fix will be available in the next (minor) release.

**Comment by thuryn** [comment]
Fixed in v. 3.0.1

**Comment by bderembl** [comment]
thanks!
in 3.0.7, it looks like the manual update is only possible for location >1 (not location 0)
