### ISSUE TITLE
Bug Found in "Your Local Weather" App (Location finder button are not working properly) 

### ISSUE THREAD

**Issue by rizwankhan003** [thuryn/your-local-weather#35]
#### Expected behavior
I Expected that when i opened "your local weather" app and active GPS location to search current city automatically and show its whether as you click on find your location whether button.

#### Actual behavior
When I opened "your local weather" app and active my phone GPS that will help the application to access location and when i click on search wheather with GPS button automatically He has searched  my current location but nothing was found then i cancel searching and again click on search wheather button and this time the button will not work.

#### How to reproduce
1. Download "Your Local Weather" App from the play store

2. Lunched the app and Run it

3. Access your GPS Location

4. Now open app and click on find current location wait for a while and cancel it

5. Again click on find current location 

6. Note the bug 
+ Your local weather Version 3.0.8
* Browser: HUAWEI Mate 10 lite
* Operating system: Android version 7.0 

#### Recording Of The Bug
<iframe width="854" height="480" src="https://www.youtube.com/embed/Ibm7lEeNElQ?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rizwankhan/bug-found-in-your-local-weather-app-location-finder-button-are-not-working-properly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by thuryn** [comment]
I cannot reproduce this bug on version 3.0.12 and 3.0.13. Which version have you tried?

**Comment by MisterY** [comment]
I've just installed the app for the first time, v4.4.6, and I see no location button at all. I went to the location list and selected the location on the map manually.
