### ISSUE TITLE
Custom API key for OWM support

### ISSUE THREAD

**Issue by SkyWheel** [thuryn/your-local-weather#40]
Hi,
Please consider to add an option to add custom API key for OpenWeatherMap queries.
Thank you!

**Comment by SkyWheel** [comment]
You can look on the custom API implementation in this repo https://github.com/martykan/forecasti.  This is also OWM app for android

**Comment by thuryn** [comment]
Implemented in 4.1.4 version

**Comment by SkyWheel** [comment]
Oh, thanks for that! Looking forward to update it from F-Droid!🙂
