### ISSUE TITLE
Cannot install "different signature to installed version"

### ISSUE THREAD

**Issue by Hund** [thuryn/your-local-weather#54]
I'm trying to install this application via F-Droid on my Nexus 5X with LineageOS 15.1, but F-droid gives me this message:

> Different signature to installed version

What's up with that?

**Comment by ildar** [comment]
You originally installed from the different source (Google Play?). You
can't change the source other then by uninstalling

**Comment by Hund** [comment]
No, this is my first time installing this application.

**Comment by ildar** [comment]
You sure? What buttons you see in Play Market app here?
https://play.google.com/store/apps/details?id=org.thosp.yourlocalweather
Install/uninstall/open?

**Comment by Hund** [comment]
I don't have Play Store, but I do have Yalp Store for a select few applications and it only asks me if I want to install it.

**Comment by Hund** [comment]
That's weird, I download's the file from Yalp Store and it let me install it. And after I uninstalled it there F-Droid allowed me to install their version?

I have no idea why and how, but since I kinda solved it I'm closing the issue. :)
