### ISSUE TITLE
Application failed to vibrate after updating the weather

### ISSUE THREAD

**Issue by adisalat2** [thuryn/your-local-weather#58]
Project Information
.Repository
https://github.com/thuryn/your-local-weather

Project Name :Your local weather

Expected Behaviour
There should vibration when weather is been updated when vibration feature is switch on

Actual Behaviour
There is no vibration when weather is been updated when vibration feature is on

How to reproduce
Download the app from fdroid
Install and run the app
Allow the app to get your location
Click the 3 lines on the top left
Select settings
Then choose General setting
Enable Notification and Vibrate
Go and update or refresh the weather condition

.Browser: Your local weather v 3.1.7
.Operating System: Android 5.1

**Comment by thuryn** [comment]
obsolete
