### ISSUE TITLE
"Broken clouds" untranslatable

### ISSUE THREAD

**Issue by comradekingu** [thuryn/your-local-weather#59]
![landing](https://user-images.githubusercontent.com/13802408/41609233-989b5e66-73ea-11e8-93fe-4c5e48aad767.png)

For the fully translated nb_NO

**Comment by thuryn** [comment]
You are able to specify translation for weather condition now (it's new feature ... just a few days). When you translate the weather conditions, I'm able to force the app to use it ;-)

**Comment by thuryn** [comment]
fixed in version 4.4.9
