### ISSUE TITLE
"ylw has stopped" during phone call

### ISSUE THREAD

**Issue by AeliusSaionji** [thuryn/your-local-weather#6]
Could be a coincidence, but just in case it's not:

I have the widget set to "wake up with display" every 15min. I wonder if the routine meant to wake up the display conflicted with a phone call on top of the lock screen?

Android 8.1 / pixel 2 xl

**Comment by thuryn** [comment]
Which version of the app have you faced this problem on?
First I would like to ask you to install the newest version (unfortunately I have still trouble to publish on f-droid.org so the version there is obsolete). When I open the app on google playstore for your country, are you willing to install the app from there? If so, send me, please, name of your country.
I havn't got device with Android 8.1 - I can try it in emulator, but this kind of problems is not easy to reproduce in emulator. So I would like to ask you to grab logs from the app (and from logcat if possible). You can enable logs in the app when you go to Settings/Debug options and check Log to file checkbox and set directory by Select directory for logging option. When you experience the problem, send me the log file, please - you can remove your location informations from the log file or accept the fact that I can see it.
Thank you a lot for help and reporting.

**Comment by AeliusSaionji** [comment]
I am using the F-Droid version. I'll try to reproduce this on the Google play version for you.

**Comment by AeliusSaionji** [comment]
The Google play version is not available in my country D:

**Comment by AeliusSaionji** [comment]
Could you perhaps upload an apk to the GitHub releases page?

**Comment by thuryn** [comment]
Yes, I can, but better open the app for your country on google play. Could you, please, tell me your country? If not, I'll put the app in the repository here.

**Comment by thuryn** [comment]
And one good news from me. Somebody called me today, but I haven't pick the phone up. And I've found, that widget has not been updated for 40 minutes. It seems it is the same issues as yours. I have logs from my phone. I'm going to investigate the problem from my logs.

**Comment by ildar** [comment]
Please also open for Kazakhstan. Thank you.

**Comment by AeliusSaionji** [comment]
My country is USA

**Comment by thuryn** [comment]
Well, I can probably see what the problem is. When you make a call the network connection is disabled (by Android). When widget wants to update during phone call it updates lastWeatherUpdated property to current time first and then it tries to make a connection. But the connection fails because of phone call.
So I'm going to modify the logic and I'll add handler for network connection recovery too.

The next version will be available for USA. I'm working on a f-droid build too to get it to work.

Thank you for reporting.

**Comment by thuryn** [comment]
Regarding of build on f-droid - there is some issue not related to my app. When I've asked f-droid support they answered: General buildserver problem again... nothing related to the app. :-/
So we can see the same version on f-droid as in google play soon ;-)

**Comment by thuryn** [comment]
I've published the fix of this issue - let's test it. The fix is present in 1.7.1 version (available on google play). It seems that that build on f-droid passes too, but I cannot see the most recent version on f-droid - so we will see.

**Comment by AeliusSaionji** [comment]
I think the problem is solved, I'll just reopen this issue if it happens again.

Thanks!
