### ISSUE TITLE
light writing on light background

### ISSUE THREAD

**Issue by thot1** [thuryn/your-local-weather#63]
Since the last update, the dark theme under Day Prediction is light writing on light background. Deleting data/reinstalling the app is not successful
![screenshot_your_local_weather_20180620-140243 1](https://user-images.githubusercontent.com/10061349/41657341-64ef512c-7493-11e8-9594-2931ae117f71.png)

**Comment by mase76** [comment]
I can confirm this.

**Comment by mase76** [comment]
Fixed in 3.2.2.

**Comment by thuryn** [comment]
Yes, it's fixed in 3.2.2
