### ISSUE TITLE
YLW updates only the last location

### ISSUE THREAD

**Issue by sitaramc** [thuryn/your-local-weather#65]
Hi

Thanks for a great piece of software; I'm really enjoying it -- especially love the transparent widget.

The problem I have is that if I add any other Locations beyond "Location 0", updates only happen for the last one (i.e., if I added two more, only Location 2 gets updated every 15 minutes).

I've now removed the 2 other cities I wanted to track, retaining only "Location 0" (the automatically discovered one), so it works OK, but I'd really like to have those cities back!

-   YLW 3.2.3, installed from F-Droid
-   all update periods and notification refresh set to 15 minutes for now
-   location and address source: "Local MLS and Nominatim (recommended)"
-   wake-up strategy: no wake up

Let me know if you need any more details, or a debug log.

Thanks.

**Comment by thuryn** [comment]
obsolete
