### ISSUE TITLE
[FR] Temperature graph : display time of day

### ISSUE THREAD

**Issue by breversa** [thuryn/your-local-weather#67]
Hi,

As of v3.2.3, on the temperature graph, there's no **precise** way to tell the time on the X axis.

For instance, I'd like to tell when a day start/ends, or when will the temperature be at its highest/lowest. At the moment, I can guesstimate, but that's it.

I know I can  check the daily forecast for that, but it'd be more explicit on the graph.

Adding vertical dotted line (like it's done for the Y axis) for 0h, 6h, 12h, and 18h each day would be a good start.

**Comment by ildar** [comment]
Actually to see the details of the graph you can simply zoom in.
But unfortunately the axis aren't right on zoom showing like: Mon Mon Mon
Mon ☺
