### ISSUE TITLE
Widget breaks

### ISSUE THREAD

**Issue by AeliusSaionji** [thuryn/your-local-weather#7]
Same issue as https://github.com/qqq3/good-weather/issues/31

This didn't happen while I had the widget updating every 15 minutes using "wake display". Now that I've switched to update every hour and "no wake up strategy", tapping my widget no longer opens ylw, and the widget theme is not what I have it set to. Nor has it updated for many hours.

**Comment by thuryn** [comment]
I'll try to reproduce this issue on the most recent version.

**Comment by thuryn** [comment]
I can confirm the bug, but still investigating the problem

**Comment by thuryn** [comment]
Fixed. Fix is inspired by patch from https://github.com/Trogel. Thank you Trogel.

**Comment by AeliusSaionji** [comment]
Seems to be working, thanks!
