### ISSUE TITLE
please update on f-droid

### ISSUE THREAD

**Issue by fenix-soft** [thuryn/your-local-weather#72]
please update the (V 4.1.4) on f-droid,  the corrent version is old and don't work (version 4.1.2) or put a link of update apk.  some peaple don't use playstore for update but f-droid

tanks

sorry for my bad english

**Comment by thuryn** [comment]
f-droid.org is really slow to build the new version, this is really not good. You can download the new version from here https://your-local-weather.en.aptoide.com/ also, but the sign is not the same as on f-droid
