### ISSUE TITLE
minSdkVersion raise

### ISSUE THREAD

**Issue by ildar** [thuryn/your-local-weather#8]
Good-Weather's value is 14, yours is 19 from the initial commit. So I can't figure out what commit did it and why.
I wonder if it was necessary and will it be possible to use on my JB tablet?

**Comment by thuryn** [comment]
I see, I'll check it and I'll do my best to bring the app to your tablet.

**Comment by thuryn** [comment]
I've published the fix of this issue. The fix is present in 1.7.1 version (available on google play). It seems that that build on f-droid passes too, but I cannot see the most recent version on f-droid - so we will see.

**Comment by ildar** [comment]
thanks a lot!!!

**Comment by ildar** [comment]
Yep, on Jelly Bean exactly like on Marshmallow.
