### ISSUE TITLE
Lead to fatal crash on LineageOS 15.1 without GApps

### ISSUE THREAD

**Issue by binarious** [thuryn/your-local-weather#84]
After installing and setting up this app, my phone began to freeze:
```
--------- beginning of crash
10-23 20:28:00.170  4592  4592 E AndroidRuntime: FATAL EXCEPTION: main
10-23 20:28:00.170  4592  4592 E AndroidRuntime: Process: org.thosp.yourlocalweather, PID: 4592
10-23 20:28:00.170  4592  4592 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
```
Nothing serious in the lines above. The phone reboots shortly after this. Wiping caches didn't help. After every reboot the phone began to freeze when starting to navigate in the OS. I did even try to flash a newer Lineage build without success.

After quickly removing this app, my problem disappeared. 

I don't know the real root cause. Let me know if my full logcat would be helpful.

- LineageOS 1.51-20181022-nightly
- OnePlus 5T
- App version 4.3.1 via f-droid (just saw [4.3.2](https://github.com/thuryn/your-local-weather/releases/tag/v4.3.2), maybe this helps? Scared to try.)

**Comment by thuryn** [comment]
Try to follow last 5 comments in #64 
If it does not help, tell to me, please

**Comment by adolfintel** [comment]
I have the same problem, the phone doesn't completely freeze (still responds to buttons) but the screen is frozen. This also happens if I try to add a widget from this app.

Lineage 15.1 with no GAPPS
Oneplus 3T

**Comment by ShadyGaDa** [comment]
Freezes at initial configuration guide screen.
On los151 Samsung j5.

**Comment by SmilingHorse** [comment]
I have the same problem on the latest LineageOS with microG (nexus 4 mako). Workaround:
0. Uninstall Your local weather.
1. Install 4.3.3.
2. In App Info enable all permissions (before first run).
3. In Battery, disable Battery Optimization (before first run).
4. Turn on Location (before first run).
5. Works; Walk through the initial setup steps. Might crash at the end but will work next time.
6. Upgrade to the latest version.

Caveat: Widget doesn't seem to work.

**Comment by adolfintel** [comment]
It's good to have a workaround, but I'd still like to know how an app that doesn't even have root permissions can completely freeze the system UI.
Is it a bug caused by lineage?

**Comment by SmilingHorse** [comment]
Well, in my case out of, say, 20 retries, I only had one ui freeze and it only lasted under 10 seconds before the app crashed. Honestly I can't even reproduce the crash so maybe it's not the same problem but it felt similar enough and I figured if my workaround works for you then you could git disect between 4.3.3 and the following version and find out what's triggering it regardless.

If it doesn't help I guess I'll retract and open a separate issue.

**Comment by adolfintel** [comment]
I'd just like to hear something from the developer of this application. I've never seen anything like it, it could be a bug in lineage that's worth reporting, or even android itself.

**Comment by thuryn** [comment]
Thank all of you for comments. I would like to see my app working on Lineage also. I don't have any device nor the virtual one to test my app on this OS. So it would be great if somebody can post application and logcat logs.

**Comment by adolfintel** [comment]
This is the error that I'm currently getting. It's no longer crashing the phone at least.
```
2018-11-11 13:03:08.126 23799-23799/org.thosp.yourlocalweather E/ActivityThread: Service org.thosp.yourlocalweather.service.StartAppAlarmJob has leaked ServiceConnection org.thosp.yourlocalweather.service.StartAppAlarmJob$1@1dc0b08 that was originally bound here
    android.app.ServiceConnectionLeaked: Service org.thosp.yourlocalweather.service.StartAppAlarmJob has leaked ServiceConnection org.thosp.yourlocalweather.service.StartAppAlarmJob$1@1dc0b08 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1532)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1424)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1605)
        at android.app.ContextImpl.bindService(ContextImpl.java:1557)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
        at org.thosp.yourlocalweather.service.StartAppAlarmJob.onStartJob(StartAppAlarmJob.java:33)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
2018-11-11 13:03:08.147 23799-23799/org.thosp.yourlocalweather D/AndroidRuntime: Shutting down VM
2018-11-11 13:03:08.148 23799-23799/org.thosp.yourlocalweather E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thosp.yourlocalweather, PID: 23799
    java.lang.NullPointerException: Attempt to invoke virtual method 'long org.thosp.yourlocalweather.model.CurrentWeatherDbHelper$WeatherRecord.getLastUpdatedTime()' on a null object reference
        at org.thosp.yourlocalweather.service.CurrentWeatherService.startCurrentWeatherUpdate(CurrentWeatherService.java:176)
        at org.thosp.yourlocalweather.service.CurrentWeatherService$CurrentweatherMessageHandler.handleMessage(CurrentWeatherService.java:434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
2018-11-11 13:03:08.151 1377-9302/system_process W/ActivityManager:   Force finishing activity org.thosp.yourlocalweather/.MainActivity
2018-11-11 13:03:08.165 1377-1678/system_process I/ActivityManager: Showing crash dialog for package org.thosp.yourlocalweather u0
```

**Comment by thuryn** [comment]
thank you a lot @adolfintel  I believe I can fix it now ;-)

**Comment by SmilingHorse** [comment]
Much better now. There still the crash at the end of the first setup procedure but there's no need to regress to an earlier version anymore to install. Also, the widget works now too. Currently what I do is:

1. Install latest version.
2. In App Info enable all permissions (before first run).
3. In Battery, disable Battery Optimization (before first run).
4. Turn on Location (before first run).
5. Walk through the initial setup steps. Might crash at the end.
6. Everything works now including the widget.

That's with LineageOS+microG 15.1 mako (Nexus 4) and the Fdroid version of Your local weather 4.4.5.
Caveat: Widget doesn't seem to work.

**Comment by thuryn** [comment]
Could somebody try the version 4.4.5 or newer, please? If the issue is still here, could you, please, put the log here?

**Comment by adolfintel** [comment]
Just tried 4.4.6 from F-Droid and it works fine.

I have a suggestion for improving user experience though:
When you first run the app, it shows way too much stuff. You should ask for permissions, use the default settings, and let the user change the settings later.

**Comment by binarious** [comment]
Nothing has changed for me. Instant freeze on first launch (did not try any of the workarounds).
Here is my logcat starting from the time where I've downloaded the app: https://gist.github.com/binarious/418340eaa6581e568d0ed5d6b76b0c9d

**Comment by gia-goldy** [comment]
Version 4.5.2 from F-Droid, instant freeze on first launch YLW.

- In App Info enable all permissions (before first run) - fixes the problem and it doesn't freeze

lineageOS-15.1 (lineage-15.1-20181219-nightly-x2-signed.zip) - twrp-3.2.3-1-x2
LeEco Le_Max 2 Phone - without GApps

**Comment by kabo** [comment]
Version 4.6.2 from F-droid, totally crashes my Nexus 6P with Lineage. I had to be REALLY quick to uninstall it after booting up, or it would crash again.

**Comment by adolfintel** [comment]
@kabo I can confirm, the bug is back. Last I checked was version 4.4.6 and it worked fine. Go figure

**Comment by thuryn** [comment]
really sorry for this. Can somebody send me logcat to see the error?

**Comment by jedie** [comment]
Think i have the same Problem on `Sony Xperia XA2 model H3113` with `lineage-15.1-20190111-nightly-pioneer-signed.zip`:

After i installed your local weather the phone freeze... It freezes every time after a start in a few seconds.

I didn't have USB debugging on, so i can't create a logcat :(


IMHO this is a VERY big bug. So the buggy version should be removed from f-droid.

**Comment by jedie** [comment]
Here a way to recover the phone:

Start in "recovery" (e.g.: Volume Up + USB-Cable insert) see combination on wiki page for your device here: https://wiki.lineageos.org/devices/

In TWRP you can run adb commands. I don't know if this works in LineageOS Recovery, too. If not: start in bootloader mode and boot into twrp with e.g.: `fastboot boot twrp-XXXX.img`

If you can run "adb commands", it should be enough to run: `adb uninstall org.thosp.yourlocalweather`
In my case it doesn't work: It's result only in: `/sbin/sh: cmd: not found`

So i looked around:
```
# adb shell ls -la /data/data
...
drwx------    6 u0_a86   u0_a86        4096 Jan 12 14:36 org.thosp.yourlocalweather
...
# adb shell ls -la /data/app
...
drwxr-xr-x    4 system   system        4096 Jan 12 14:20 org.thosp.yourlocalweather-DUE3up5ftcMPe_IoOx7vNA==
...
```
and deinstall by delete the app via `adb shell`, e.g.:
```
# adb shell
~ # rm -Rf /data/data/org.thosp.yourlocalweather/
~ # rm -Rf /data/app/org.thosp.yourlocalweather-DUE3up5ftcMPe_IoOx7vNA\=\=/
~ # exit
```

After this my phone doen't freeze ;)

**Comment by thuryn** [comment]
Can somebody, try the (prerelease) version here: https://de-next.owncube.com/index.php/s/zie8dYZqT63W7q4 (as I don't have Lineage to test). Thanks a lot

**Comment by adolfintel** [comment]
@thuryn your APK doesn't crash for me.

**Comment by poiNt3D** [comment]
I get this crash on LineageOS 13.
Prerelease version doesn't help.

**Comment by adolfintel** [comment]
@thuryn I'm trying to help the devs of Osmand fix this same exact problem, can you explain what you changed to fix it? Thanks
