### ISSUE TITLE
Persistent status bar notification

### ISSUE THREAD

**Issue by thuryn** [thuryn/your-local-weather#90]
from email:
A persistent status bar notification would be great, maybe showing a small icon and the temperature, with more information on swiping downwards. Right now I have to unlock my phone to get any information.

**Comment by infinitewaveparticle** [comment]
The temperature would be best for the status bar notification (instead of the weather icon)

**Comment by doctor-owl** [comment]
Agreed, I switched to this app since none of the play store ones auto update & I wanted an open source option, but having no status bar notification kinda sucks. Would be nice to see the temperature at a quick glance without unlocking phone. App is great otherwise ;)

**Comment by thuryn** [comment]
I'm going to implement these changes:
- add an option to show notification just on the lock screen
- add an option to fire notification when update by regular scheduler occurs
- add an option to show permanent notification
- add an option to show temperature/icon/nothing in the status bar
