### ISSUE TITLE
Map cannot be displayed

### ISSUE THREAD

**Issue by linsui** [thuryn/your-local-weather#92]
When I add a location,  the map cannot be displayed. But I can still click to get a location.

**Comment by linsui** [comment]
![screenshot_20181119-183906](https://user-images.githubusercontent.com/36977733/48701920-96590c80-ec2a-11e8-9679-d502ae2b6003.png)

**Comment by thuryn** [comment]
What is the location where it does not work (approximately)? Are you able to see something on different part of the world? Is it possible that your Internet provider blocks openstreermap.org website?

**Comment by EthanArmbrust** [comment]
This is happening for me as well. I'm in the northeast of USA. I've tried on multiple networks, and I can access openweathermap and openstreetmap in a browser just fine, so I doubt it is a network blocking issue. Happening in android 9 on a pixel xl and on an emulator.

**Comment by linsui** [comment]
I can't see map anywhere. I can access www.openstreermap.org in browser. This problem appear only in 4.3+. I don't know the exectly version. I find this problem when I reinstall app so it may appear on early version.

**Comment by thuryn** [comment]
I see, I can see it in the emulator also. So I can check and fix it. Thank you.

**Comment by thuryn** [comment]
I've just found the problem: Starting with Android 9.0 (API level 28), cleartext support is disabled by default. And the exception:
IOException: Cleartext HTTP traffic to b.tile.openstreetmap.org not permitted

**Comment by thuryn** [comment]
fixed in v4.4.8
