### ISSUE TITLE
Cannot add more than one location.

### ISSUE THREAD

**Issue by linsui** [thuryn/your-local-weather#93]

**Comment by linsui** [comment]
![screenshot_20181119-183824](https://user-images.githubusercontent.com/36977733/48702012-c7d1d800-ec2a-11e8-88e5-ed3b3eb1e6d2.png)
![screenshot_20181119-183928](https://user-images.githubusercontent.com/36977733/48702023-cbfdf580-ec2a-11e8-8fa3-f12ca06bafb6.png)

**Comment by thuryn** [comment]
This is not the bug, it's a feature. The reason for limit of 2 locations is in fact, that app access openweathermap.org with API key with limited number of connections. I'm working on some solution to provider commercial access to openweathermap.org - it's going to be paid.
Sorry for inconvenience.

**Comment by sm4rk0** [comment]
Fair enough, but it should be explained to the user. For example, leave the + button, but fire a dialog or a toast with an explanation.

**Comment by sotel** [comment]
There's no notice in the **changelog**.
Please announce such changes there.
