### ISSUE TITLE
Crash on fresh installation for 4.4.9 (97)

### ISSUE THREAD

**Issue by sm4rk0** [thuryn/your-local-weather#95]
After fresh installation (or wiping data), Your local weather crashes immediately. Here's a [logcat](https://gist.github.com/sm4rk0/7f203f3f6776ba392a57724ccf5076f3).

**Comment by MisterY** [comment]
I can confirm. The first installation on a phone with Android 7.

**Comment by MisterY** [comment]
I can confirm. This should be closed.
