### ISSUE TITLE
Widget not auto updating

### ISSUE THREAD

**Issue by infinitewaveparticle** [thuryn/your-local-weather#98]
Version 4.4.6
Android 8.1

Everything seems to be working fine other than the widget not updating automatically. The notification updates just fine. The notification Refresh Interval & the Update Period for Weather are each set to 30 minutes. I would assume that when the weather updates that both the notification and the widget would display the new values. Instead the widget just remains the same along with the last manually updated time.

**Comment by thuryn** [comment]
I've just found the problem of location updates for location zero. But when I start to thing of this feature I found it's not so easy. So I would like to ask you what is your expectation for this scenario. Notification service updates current weather only in the current implementation. The update of location 0 should update location, current weather and weather forecast (it's fixed right now, not released).

There are several examples how it could be implemented:
1) Notification updates everything and disabled update by the Update period interval
2) Notification just takes the current weather updated by Update period interval
3) Some other combination or idea?

**Comment by thuryn** [comment]
fixed in version 4.5.0

**Comment by infinitewaveparticle** [comment]
I'll update the app, but just for reference I don't uae Location 0 or auto location. My GPS and location on my device are permanently off.

**Comment by infinitewaveparticle** [comment]
I only use my manually entered location.

**Comment by thuryn** [comment]
Does the update work for you with the newest version or not?

**Comment by infinitewaveparticle** [comment]
Yes, thank you

**Comment by infinitewaveparticle** [comment]
Actually I just updated the app today to version 4.6.1 and it's no longer updating again.
