### ISSUE TITLE
Show measured temperature in the Daily Forecast

### ISSUE THREAD

**Issue by MisterY** [thuryn/your-local-weather#99]
The daily forecast currently shows the perceived, not actual, temperature. This can be useful and I would like to have it there but can be misleading. It would be really useful to have the measured temperature in the list, too. This really helps when comparing the weather conditions between different locations or data sources.

**Comment by sm4rk0** [comment]
There's setting for which columns to be shown i overflow menu (vertical three dots i upper right corner of the screen).

**Comment by MisterY** [comment]
Oh, thanks a lot! Never noticed that one.
